{% set name = "perl-bio-phylo-cipres" %}
{% set version = "0.0.1" %}
{% set sha256 = "afc356265e723e0274840238a4b046e51c3aa58acbdf05aedc71a6fd61f68144" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Bio-Phylo-CIPRES-0.0.1.tar.gz
  url: https://cpan.metacpan.org/authors/id/R/RV/RVOSA/Bio-Phylo-CIPRES-0.0.1.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  build:
    - perl
    - perl-yaml
    - perl-bio-phylo
    - perl-extutils-makemaker
    - perl-xml-twig
    #- perl-test-more

  run:
    - perl
    - perl-yaml
    - perl-bio-phylo
    - perl-xml-twig

test:
  # Perl 'use' tests
  imports:
    - Bio::Phylo::CIPRES

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Bio::Phylo::CIPRES
  license: perl_5
  summary: 'Client for the CIPRES analysis portal'

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
