{% set name = "perl-bio-cipres" %}
{% set version = "0.005" %}
{% set sha256 = "1c8b4e754cf7ac2e190fe24b79a3dc203a1398e21de9b7cf5642dc080115fa57" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: Bio-CIPRES-0.005.tar.gz
  url: https://cpan.metacpan.org/authors/id/V/VO/VOLKENING/Bio-CIPRES-0.005.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  build:
    - perl
    - perl-config-tiny
    - perl-module-build
    - perl-xml-libxml
    - perl-lwp-protocol-https
    - perl-net-ping
    - perl-time-piece
    - perl-uri

  run:
    - perl
    - perl-time-piece
    - perl-uri
    - perl-xml-libxml
    - perl-lwp-protocol-https
    - perl-config-tiny

test:
  # Perl 'use' tests
  imports:
    - Bio::CIPRES
    - Bio::CIPRES::Error
    - Bio::CIPRES::Job
    - Bio::CIPRES::Message
    - Bio::CIPRES::Output

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Bio::CIPRES
  license: gpl_3
  summary: 'interface to the CIPRES REST API'

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
